### ISSUE TITLE
Opening Screen on Server Throws Error in 1.18.2

### ISSUE THREAD

**Issue by IAmSneak** [pcal43/copper-hopper#19]
With polymer on the server, the hopper doesn't open and the server throws the following error in logs but doesn't crash

`
[09:35:47] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@18d2c2b2, suppressing error
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at net.pcal.copperhopper.CohoService.getScreenHandlerType(CohoService.java:72) ~[copperhopper-0.0.5+1.18.1.jar:?]
        at net.pcal.copperhopper.CohoScreenHandler.method_17358(CohoScreenHandler.java:20) ~[copperhopper-0.0.5+1.18.1.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1038) ~[server-intermediary.jar:?]
        at net.minecraft.class_2377.method_9534(class_2377.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.redirect$zfg000$activateWithOptionalCactus(class_3225.java:1529) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zci000$modifiedRunLoop(MinecraftServer.java:2905) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by pcal43** [comment]
thanks for the report.  will see if i can take a look at it next week.

**Comment by WillowMist** [comment]
I do experience the same issue if Polymer is enabled.  It works fine without it.

**Comment by IAmSneak** [comment]
Doesn't appear to be fixed in 0.0.6+1.18.2. Gives this error:
`[09:49:56] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@55205eb2, suppressing error
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at net.pcal.copperhopper.CohoService.getScreenHandlerType(CohoService.java:72) ~[copperhopper-0.0.6+1.18.2.jar:?]
	at net.pcal.copperhopper.CohoScreenHandler.method_17358(CohoScreenHandler.java:20) ~[copperhopper-0.0.6+1.18.2.jar:?]
	at net.minecraft.class_3222.method_17355(class_3222.java:1038) ~[server-intermediary.jar:?]
	at net.minecraft.class_2377.method_9534(class_2377.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.redirect$zen000$activateWithOptionalCactus(class_3225.java:1029) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbp000$modifiedRunLoop(MinecraftServer.java:2905) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by pcal43** [comment]
Hmm.  I'll take another look.  Let me ask though: do you actually care about running it in 'polymer mode?'  

I'm actually sort of thinking about removing support for it because it just isn't going to work well given the way the mod has evolved.

**Comment by IAmSneak** [comment]
Currently I would only plan to run this mod with polymer mode.  There is already a golden hopper mod that does about the same thing. But this is your mod in the end and if you don't want to support it you shouldn't feel like you have to.

**Comment by pcal43** [comment]
Ok.  Try the new version 0.0.7.  Should be better.
