### ISSUE TITLE
Error when opening hopper (Polymer)

### ISSUE THREAD

**Issue by Khikki** [pcal43/copper-hopper#23]
I paid attention to past issues, the error is similar, I can’t open the hopper, I also can’t create it on the vanilla client.
I believe that further polymer support is needed.

```[10:09:37] [Server thread/ERROR] (class_2600) Failed to handle packet net.minecraft.class_2885@24c8eedb, suppressing error
 java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at net.pcal.copperhopper.CohoService.getScreenHandlerType(CohoService.java:72) ~[copperhopper-0.0.7+1.18.2.jar:?]
        at net.pcal.copperhopper.CohoScreenHandler.method_17358(CohoScreenHandler.java:20) ~[copperhopper-0.0.7+1.18.2.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1038) ~[server-intermediary.jar:?]
        at net.minecraft.class_2377.method_9534(class_2377.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.redirect$zll000$activateWithOptionalCactus(class_3225.java:1529) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.redirect$zfo000$redirectExecuteTask(class_1255.java:521) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:12288) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zin000$modifiedRunLoop(MinecraftServer.java:3905) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by pcal43** [comment]
Again, looks to me like you didn't follow the instructions in copperhopper.properties

```

#
# Uncomment this line if you want to run CopperHopper on a server that works with vanilla clients or clients
# that don't have the mod installed.  CopperHoppers will appear as regular Hoppers on those clients but they
# will function normally.
#
# In order for this to work, you need to also have the polymer mod installed: https://polymer.pb4.eu
#
# polymer-enabled = true

```
