### ISSUE TITLE
Sadly does not work with 1.19 even after updating fabric.mod.json

### ISSUE THREAD

**Issue by Greg-J** [pcal43/copper-hopper#26]
Sadly does not work with 1.19 even after updating fabric.mod.json. I get the following crash:
```

[12:19:55] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'copperhopper'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.7.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.7.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.7.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.7.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19-loader.0.14.7-launcher.0.11.0.jar:0.11.0]
Caused by: java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    net/pcal/copperhopper/polymer/PolymerCopperHopperBlock.method_9518()Lnet/minecraft/class_5250; @13: areturn
  Reason:
    Type 'net/minecraft/class_2585' (current frame, stack[0]) is not assignable to 'net/minecraft/class_5250' (from method signature)
  Current Frame:
    bci: @13
    flags: { }
    locals: { 'net/pcal/copperhopper/polymer/PolymerCopperHopperBlock' }
    stack: { 'net/minecraft/class_2585' }
  Bytecode:
    0000000: bb00 4259 b800 48b6 004c b700 4fb0

        at net.pcal.copperhopper.polymer.PolymerRegistrar.run(PolymerRegistrar.java:26) ~[copperhopper-0.0.8+1.18.2.jar:?]
        at net.pcal.copperhopper.CohoInitializer$ExactlyOnceInitializer.<clinit>(CohoInitializer.java:48) ~[copperhopper-0.0.8+1.18.2.jar:?]
        at net.pcal.copperhopper.CohoInitializer.onInitialize(CohoInitializer.java:29) ~[copperhopper-0.0.8+1.18.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.7.jar:?]
        ... 8 more
 
```

**Comment by pcal43** [comment]
Yeah, unfortunately I'm basically dropping support for polymer. It's just too much trouble, I don't have time, and I don't actually use it myself anymore.

If you know how to fix it and want to send me a PR, I'd be happy to take a look, though.
