### ISSUE TITLE
[Bug] Could not execute entrypoint stage 'main' due to errors, provided by 'copperhopper'

### ISSUE THREAD

**Issue by gkr0013** [pcal43/copper-hopper#56]
Dear,

with the last version (copperhopper-0.5.0+1.20.1.jar), on server Fabric 1.20.1, i have a bug :
(no problem with copperhopper-0.4.0+1.20.1.jar, only 0.5.0)

Minecraft 1.20.1 with Fabric Loader 0.14.21

[07:09:18] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[07:09:18] [ForkJoinPool-1-worker-7/WARN]: Mod allstackable uses the version v2.0.0-1.20.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:09:18] [main/INFO]: Loading 155 mods:
	- additionalstructures 4.2.0
	- allstackable v2.0.0-1.20.1
	- anvilrestoration 2.0
	- architectury 9.1.12
	- bakery 1.1.2
	- balm-fabric 7.1.4
	- betterconduitplacement 3.0
	- betterdeserttemples 1.20-Fabric-3.0.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.2
	- betterfortresses 1.20-Fabric-2.0.3
	- betterjungletemples 1.20-Fabric-2.0.2
	- bettermineshafts 1.20-Fabric-4.0.3
	- betteroceanmonuments 1.20-Fabric-3.0.2
	- betterspawnercontrol 4.2
	- betterstrongholds 1.20-Fabric-4.0.2
	- betterwitchhuts 1.20-Fabric-3.0.2
	- biggerspongeabsorptionradius 3.1
	- blossom 1.0.7
	- bookshelf 20.0.4
	- bottleyourxp 3.1
	- candlelight 1.2.4
	- chunkloaders 1.2.7+a
	- chunksending 1.20.1-2.6
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- coinsje 12.0.1
	- collective 6.66
	- copper_pipe 1.13.6
	- copperhopper 0.5.0+1.20.1
	- cropped 1.0.1
	- cupboard 1.20.1-2.0
	- despawningeggshatch 4.1
	- dismountentity 3.0
	- doapi 1.2.7
	   |-- blue_endless_jankson 1.2.1
	   \-- terraform-wood-api-v1 7.0.1
	- doubledoors 5.0
	- easyelytratakeoff 4.0
	- elytraslot 6.3.0+1.20.1
	- extendedbonemeal 3.0
	- fabric-api 0.88.1+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.3+92a0d36777
	   |-- fabric-renderer-indigo 1.4.3+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.1+195226a777
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.14.21
	- fallingtree 4.3.0
	- ferritecore 6.0.0
	- fixedanvilrepaircost 3.1
	- forcecrawl 1.0.2
	- forgeconfigapiport 8.0.0
	- furnacerecycle 2.0
	- grindenchantments 3.1.2+1.20
	   \-- codec-config-api 1.0.2+1.19.3
	- healingcampfire 5.1
	- hoetweaks 3.2
	- huskspawn 3.3
	- imst 2.1.0
	- imst_n 1.0.0
	- inventorysorter 1.9.0-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- jade 11.5.1
	- java 17
	- jei 15.2.0.27
	- justmobheads 7.3
	- keepmysoiltilled 2.0
	- kleeslabs 15.0.0
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazydfu 0.1.3
	- lithium 0.11.2
	- magnumtorch 8.0.0
	- microcutting 1.20-rc1-1.5.0
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- mixin-conflict-helper 1.2.0
	- mooshroomtweaks 3.2
	- naturallychargedcreepers 3.2
	- neruina 1.2.3
	   |-- com_github_llamalad7_mixinextras 0.2.0-rc.4
	   \-- mixinsquared 0.0.2
	- netherportalfix 13.0.0
	- notenoughcrashes 4.4.6+1.20.1
	- petnames 3.0
	- puzzleslib 8.0.24
	- replantingcrops 5.1
	- repurposed_structures 7.1.6+1.20.1-fabric
	- scaffoldingdropsnearby 3.0
	- separatedleaves 2.2.0
	- skeletonhorsespawn 3.6
	- smallernetherportals 3.4
	- smart-villagers-follow-emeralds 1.0.0
	- smoothchunk 1.20.1-3.2
	- softerhaybales 3.0
	- spark 1.10.53
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- stackrefill 4.0
	- starlight 1.1.2+fabric.dbc156f
	- structureessentials 1.20.1-3.0
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.12+d
	- tntbreaksbedrock 3.0
	- toofast 1.2.0
	- trade_cycling 1.20.1-1.0.7
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da82
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b82
	- trinkets 3.7.1
	- universalenchants 8.0.0
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   \-- extensibleenums 7.0.1
	- vanityslots 1.2.9
	- villagernames 5.2
	- villagersplus 2.1
	- vinery 1.4.4
	- weakerspiderwebs 3.2
	- wooltweaks 3.1
	- yungsapi 1.20-Fabric-4.0.1
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.2
	- yungsextras 1.20-Fabric-4.0.2
	- zombiehorsespawn 4.6
[07:09:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[07:09:19] [main/INFO]: Compatibility level set to JAVA_17
[07:09:21] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[07:09:21] [main/WARN]: @Mixin target net.coderbot.iris.Iris was not found notenoughcrashes.fabric.mixins.json:iris.SilentNEC from mod notenoughcrashes
[07:09:21] [main/INFO]: Loaded config for: structureessentials.json
[07:09:21] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0-rc.4).
[07:09:39] [main/INFO]: [All Stackable] Start loading!
[07:09:39] [main/INFO]: [All Stackable] Command registered.
[07:09:40] [main/ERROR]: No data fixer registered for bakery:wandering_baker
[07:09:41] [main/INFO]: Registering C2S receiver with id candlelight:typewriter_sync
[07:09:41] [main/INFO]: Registering C2S receiver with id candlelight:sign_note
[07:09:41] [main/INFO]: Loaded config for: chunksending.json
[07:09:41] [main/INFO]: chunksending mod initialized
[07:09:41] [main/INFO]: Loading Collective version 6.66.
[07:09:42] [main/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
[07:09:42] [main/INFO]: Constructing common components for magnumtorch:main
[07:09:43] [main/INFO]: Initializing Neruina
[07:09:43] [main/INFO]: Constructing common components for puzzleslib:main
[07:09:43] [main/INFO]: structureessentials mod initialized
[07:09:43] [main/INFO]: Registered JSON trade offer adapter.
[07:09:43] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'copperhopper'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_897
	at net.pcal.copperhopper.CohoInitializer.onInitialize(CohoInitializer.java:70) ~[copperhopper-0.5.0+1.20.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_897
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.pcal.copperhopper.CohoInitializer.onInitialize(CohoInitializer.java:70) ~[copperhopper-0.5.0+1.20.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more

**Comment by Treeway7** [comment]
I have this error too. I'm running 1.20.1 with Quilt server 0.20.2. The mod works just fine clientside.
